# permissions for end users to view terrains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terrain-viewer-role
rules:
- apiGroups:
  - apps.axiomatic.dev
  resources:
  - terrains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.axiomatic.dev
  resources:
  - terrains/status
  verbs:
  - get
