# permissions for end users to edit terrains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terrain-editor-role
rules:
- apiGroups:
  - apps.axiomatic.dev
  resources:
  - terrains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.axiomatic.dev
  resources:
  - terrains/status
  verbs:
  - get
